### ISSUE TITLE
modified:   .DS_Store 

### ISSUE THREAD

**Issue by ashley-biu** [YUECHEN0830/DSP_Data_Geek_Solar_Energy#10]
Hi team,

The "modified:   .DS_Store" always appears when I want to switch the branch. I'm not sure why. Please find more details as below screenshot.
![Screen Shot 2020-10-25 at 19 42 49](https://user-images.githubusercontent.com/68436889/97102845-e7b68400-16fc-11eb-952b-33a4e9730775.png)

**Comment by ashley-biu** [comment]
tested and fixed the problem

**Comment by kevingyk6854** [comment]
.DS_Store is a hidden file for Mac OS. The best way to fix this problem is to add this type of file in .gitignore.
![image](https://user-images.githubusercontent.com/25969080/97103821-24857980-1703-11eb-9b6e-f92f2ba89ec7.png)
