### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by kevingyk6854** [YUECHEN0830/DSP_Data_Geek_Solar_Energy#11]
![image](https://user-images.githubusercontent.com/25969080/97103860-67dfe800-1703-11eb-96de-a23e3f3c4801.png)
![image](https://user-images.githubusercontent.com/25969080/97103864-6dd5c900-1703-11eb-81f8-45559b703870.png)
Two types of plots have been uploaded, please check the codes under this path `code/src/annual_Scenario_1.Rmd`

**Comment by rato-li** [comment]
They look good, Yukai.

In the second bar chart, can we also separate by state? That will make it comparable to the first chart, ie number of accredited installers vs number of PV systems installed.

**Comment by kevingyk6854** [comment]
Yes, we could, but probably bar chart might be not a good choice if we put all these states in one graph. It will be a bit messy. Or, if we put these state by state, there will be eight states with eight charts. It might be too many, maybe we need get rid of some of them and choose some typical ones.

**Comment by kevingyk6854** [comment]
![image](https://user-images.githubusercontent.com/25969080/97389895-a9ed7180-192f-11eb-9e9a-5e00377b4c78.png)
How is this? @rato-li

**Comment by YUECHEN0830** [comment]
looks good!! It is more visible than the previous one
