### ISSUE TITLE
Is Ashley one of the Contributor?

### ISSUE THREAD

**Issue by rato-li** [YUECHEN0830/DSP_Data_Geek_Solar_Energy#3]
![image](https://user-images.githubusercontent.com/60586908/96998755-c8461c80-157f-11eb-8b74-edd9fc6a38f0.png)
Just noticed Ashley's name is not in the list. Please add her in.

**Comment by kevingyk6854** [comment]
<img width="748" alt="WX20201023-225915@2x" src="https://user-images.githubusercontent.com/25969080/97001244-cd0ccf80-1583-11eb-881e-ea6b982856c6.png">
According to the Github official document, if your commits in the repository are on a non-default (which is master here), you won't be in contributor graph.

**Comment by kevingyk6854** [comment]
![image](https://user-images.githubusercontent.com/25969080/97012875-0fd6a380-1594-11eb-99bb-79ec373a733f.png)
Now, she is one of the contributors. Cheers

**Comment by ashley-biu** [comment]
I'm in the contributors list now. Thanks Yukai.

**Comment by rato-li** [comment]
Issue resolved.
