### ISSUE TITLE
How to migrate a mysql database to another server

### ISSUE THREAD

**Issue by kevingyk6854** [YUECHEN0830/DSP_Data_Geek_Solar_Energy#4]
![image](https://user-images.githubusercontent.com/25969080/97069004-903ee800-1618-11eb-865a-58352d31531d.png)
As I am going to reach the limitation of free tier usage on AWS RDS, we need to change to another one for public use.
Here is something that I found about how to migrate a mysql database. Please check it. Cheers
> https://www.mysqltutorial.org/mysql-copy-database/

**Comment by rato-li** [comment]
Thanks Yukai for alerting us. 
We can move the database to my RDS. I have created a blank database on my RDS, db called the same name dsp_test. I will try to create a new user with the same username password so that we don't need to change too much in our code.

**Comment by rato-li** [comment]
I have completely migrated the database over to my RDS. Please connect to:
host: dsp-01.cnk9sarev6lg.us-east-2.rds.amazonaws.com
database: dsp_test
username: tutorial_user
password: (same as before)
