### ISSUE TITLE
One demo about downloading data set from website by R code

### ISSUE THREAD

**Issue by kevingyk6854** [YUECHEN0830/DSP_Data_Geek_Solar_Energy#6]
Under this path - `code/src/bom_solar_data_download.R`, there is one demo for downloading solar radiation data set from BOM (Bureau of Meteorology) with one function - bom_solar_data_download(). The parameter is the station number. The new data sets will be saved under this path - `data/raw_datasets`. How to use this function? Please check `code/src/data_download_test.R`.

**Comment by rato-li** [comment]
A great function. The tricky thing about downloading data from BOM is that everyday the link will change. It is the right approach to start from the URL that specifies the dataset type and station number to scrape the next and final URL for downloading. Thanks Yukai.
