### ISSUE TITLE
dbWriteTable

### ISSUE THREAD

**Issue by Marco-Sulser** [YUECHEN0830/DSP_Data_Geek_Solar_Energy#7]
The solution below did create some issues when we imported tables into an AWS RDS data base our of RStudio. We encountered that empty tables got uploaded. 

RMySQL::dbWriteTable(<db_connection>, <table_name>, <data_set>, append=TRUE, row.names=FALSE)

We have worked out a solution using `read_csv` from the `tidyverse` package to assign the table to a tibble and the we used the following command.  

RMySQL::dbWriteTable(<db_connection>, <tibble_name_object>, <data_set>, append=TRUE, row.names=FALSE)

This worked very well.

**Comment by rato-li** [comment]
This 2-step process worked perfectly. Thank you Marco.
